db
t-miki-nextat/laravel-inquiry pull request #2
Opened 2023-03-06 05:47 UTC by t-miki-nextat

宜しくお願いします！

2023-03-06 05:56 UTC, sawada-nextat commented on laravel-inquiry/app/Enums/InquiryType.php
> +use BenSampo\Enum\Enum;
PHP8.1からEnumが追加されたのでそっちを使って書いてみましょう。
森パイセンの記事が参考になります。

https://nextat.co.jp/staff/archives/276

2023-03-06 06:01 UTC, sawada-nextat commented on laravel-inquiry/app/Http/Controllers/InquiriesController.php
> +    public function index()
先を見据えて作っていただいて素晴らしいです！

ただ今回の課題(STEP2)だとこれはタスクの範囲外で、STEP3からの実装になるかなと思うので、PRには含めないほうがよさそうです。
基本的にPRは課題単位で切り、その課題に関係ないものは別PRを作成して分けたほうがレビュアーからしても分かりやすいです。

また余談ですが、同じ課題でも変更ファイルが大量に出てしまうことがよくあるのですが、そのときはおおよその機能ごとなどにPRを分けて、1PRにつき10ファイルぐらいずつに分割して出した方がいいです。

（今回はこのままで大丈夫です！）

2023-03-06 06:04 UTC, sawada-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> +class Inquiries extends Model
PHPDocを書いてみましょう。
PHPDocを書く意味についてはナカエ先生が以下の記事で解説しているので参考にしてみてください。
（ちょっと昔の記事なのでリレーション周りの書き方などが若干古いです。Laravel9くらいのPHPDocの書き方の記事なども併せて読んでおくとよさそうです。）
https://nextat.co.jp/staff/archives/146

2023-03-06 06:16 UTC, sawada-nextat commented on laravel-inquiry/app/Enums/InquiryType.php
> +<?php declare(strict_types=1);
細かいところですが、基本改行入れることが多いですね。

```
<?php

declare(strict_types=1);

namespace ~~~

```

2023-03-06 06:21 UTC, sawada-nextat commented on laravel-inquiry/database/migrations/2023_03_06_051222_create_inquiries_table.php
> +            $table->enum('type',InquiryType::getValues());
https://nextat.slack.com/archives/C04S4Q6UT6V/p1678083278819199

ってことなので、拡張可能な形に変えてみましょう。
ヒント１：今回はenumの値が文字列
ヒント２：ちょっと長めにとって50文字くらいに対応できたらOK

2023-03-07 02:25 UTC, sawada-nextat commented on laravel-inquiry/composer.json
> +        "bensampo/laravel-enum": "^6.3",
もう不要になったので消しておきましょうか

2023-03-07 02:26 UTC, sawada-nextat approved these changes

2023-03-07 07:37 UTC, takagi-nextat commented on laravel-inquiry/app/Http/Controllers/InquiriesController.php
> +
declare(strict_types=1);

2023-03-07 07:38 UTC, takagi-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> + * @property text $content inquiry_content
`text`という型はPHPにはないので、ここでは`string`が正しいです。

2023-03-07 07:42 UTC, takagi-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> + * @property text $type inquiry_type
ここではstringではなく`InquiryType`というenum型となるようにしたいです。
enum型を独自で作成してみましょう。

この辺が参考になります。
https://nextat.co.jp/staff/archives/276

2023-03-07 08:05 UTC, t-miki-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> + * @property text $type inquiry_type
https://nextat.slack.com/archives/C04S4Q6UT6V/p1678083278819199
問合せ種別については中榮さん、澤田さんからも指摘があり、拡張性を担保する為enum型ではなく一旦string型で定義しバリデーションで制限を設けることになりましたが、そちらの方法で宜しいでしょうか？

2023-03-07 08:08 UTC, sawada-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> + * @property text $type inquiry_type
DB上ではstringですが、コード上ではenum型として扱う感じですね
なのでマイグレーションは変える必要はないです

2023-03-07 08:28 UTC, t-miki-nextat commented on laravel-inquiry/app/Models/Inquiries.php
> + * @property text $type inquiry_type
コメントありがとうございます。
バリデーションのルールでenum型で制限する理解で合ってますか？

2023-03-07 10:31 UTC, ghost commented on laravel-inquiry/app/Models/Inquiries.php
> +class Inquiries extends Model
モデルの命名は単数形が原則です。（Laravelプロジェクトではテーブル名は複数形が一般的）
`Inquiry`で

2023-03-07 10:32 UTC, takagi-nextat commented on laravel-inquiry/composer.lock
> +            "name": "bensampo/laravel-enum",
この変更は必要なくなったはずでは？

2023-03-07 10:33 UTC, ghost commented on laravel-inquiry/routes/web.php
> +Route::get('/inquiries', function () {
ルーティングをグループ化してみましょう

2023-03-07 10:33 UTC, takagi-nextat commented on laravel-inquiry/routes/web.php
> +Route::get('/inquiries', function () {
今回のPRでの主目的ではないので次のPRでやってもOK

2023-03-07 10:35 UTC, takagi-nextat commented on laravel-inquiry/app/Http/Controllers/InquiriesController.php
> +class InquiriesController extends Controller
コントローラの命名は単数形（InquiryController）か複数形（InquiriesController）は使用する言語やFWによって様々で、絶対の正解があるわけではありません。
弊社でのLaravelプロジェクトでは基本的に単数形にしているので`InquiryController`としましょう。

2023-03-07 10:36 UTC, takagi-nextat requested changes
修正お願いします。
指摘の意味がわからない、直し方がわからない場合は気軽に聞いてもらってOKです！

2023-03-08 02:40 UTC, takagi-nextat commented on laravel-inquiry/app/Models/Inquiry.php
> + * @property InquiryType $type inquiry_type
今の実装のままだと実際の挙動としてはこうならないはず

2023-03-08 02:58 UTC, takagi-nextat approved these changes

2023-03-08 03:50 UTC, merged