Inquiry admin
t-miki-nextat/laravel-inquiry pull request #5
Opened 2023-03-10 07:17 UTC by t-miki-nextat

https://nextat.backlog.com/view/NXT-38
宜しくお願いします！

2023-03-10 08:31 UTC, mori-nextat requested changes

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/app/Http/Controllers/AdminController.php
> +        $inquiries = Inquiry::orderBy('created_at', 'desc')->paginate(10);
10を定数として定義しておきましょう。
`private const PER_PAGE = 10;` としておくと後からの変更が楽になります

paginate()の引数は4つのはずなんですが、あえて指定してみてください

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/app/Http/Controllers/AdminController.php
> +        $inquiries = Inquiry::orderBy('created_at', 'desc')->paginate(10);
PhpStormでorderBy()の部分にwarningが出ているかと思われます。
`Inquiry::query()->orderBy`としてみてください

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/app/Http/Controllers/AdminController.php
> +    public function show($id)
返り値の型指定とPhpDocを

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/app/Http/Controllers/AdminController.php
> +            abort(404);
レコードがない場合に404を返してくれるfindOrFail()というメソッドがあるので試してみてください

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/database/seeders/DatabaseSeeder.php
> +         \App\Models\Inquiry::factory(20)->create();
これは不要ですかね？

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/database/seeders/InquiriesTableSeeder.php
> +
不要な行が入っているように見えます。
ファイル全体をフォーマットしてみてください

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/resources/views/admin/show.blade.php
> +                    <td>{{ $inquiry->type }}</td>
「お見積り」「採用」のような表示用のテキストが出力されるようにしてください。
たしかEnumに設定したはずです

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/resources/views/admin/inquiries.blade.php
> +    <div class="container">
routeの名前にあわせて、inquiriesディレクトリを作成し、一覧はindex.blade、詳細はshow.bladeにするとディレクトリ構造が見やすくなりそうです。

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/resources/views/admin/inquiries.blade.php
> +                    <td><a href="{{ route('admin.inquiries.show', ['id'=>$inquiry->id]) }}"
このあたりはフォーマットが効かないと思いますが、スペースを入れて見やすくしてください
`['id' => $inquiry->id]`

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/routes/web.php
> +    Route::get('show/{id}', [AdminController::class, 'show'])->name('inquiries.show');
課題の指示では、詳細は`/inquiries/{id}`と指定されてますね

prefixとnameがinquiriesのグループが作れそうです

2023-03-10 08:31 UTC, mori-nextat commented on laravel-inquiry/database/factories/InquiryFactory.php
> +            'type' => 'estimate',
せっかくなので作成したEnumから値をとるようにしましょう

2023-03-12 23:53 UTC, mori-nextat approved these changes

2023-03-13 06:38 UTC, takagi-nextat approved these changes

2023-03-13 06:39 UTC, merged